"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import re
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
globals()["BASE_DIR"] = BASE_DIR


def _leer_env(clave: str, default: str = "") -> str:
    env_path = BASE_DIR / ".env"
    if "os" in globals() and os.environ.get(clave):
        return os.environ.get(clave, "")
    if not env_path.exists():
        return default
    contenido = env_path.read_text(encoding="utf-8")
    patron = re.compile(rf"^{re.escape(clave)}\s*=\s*(.+)$", re.MULTILINE)
    match = patron.search(contenido)
    return match.group(1).strip() if match else default


def _build_database_settings():
    motor = os.environ.get("DB_ENGINE", _leer_env("DB_ENGINE", "local")).strip().lower()
    database_url = os.environ.get("DATABASE_URL", _leer_env("DATABASE_URL", "")).strip()

    if motor == "nube":
        if database_url:
            parsed = urlparse(database_url)
            return {
                "default": {
                    "ENGINE": "django.db.backends.postgresql",
                    "NAME": parsed.path.lstrip("/"),
                    "USER": parsed.username or "",
                    "PASSWORD": parsed.password or "",
                    "HOST": parsed.hostname or "",
                    "PORT": parsed.port or 5432,
                    "OPTIONS": {"sslmode": "require"},
                }
            }

        return {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": os.environ.get("DB_NAME", _leer_env("DB_NAME", "")),
                "USER": os.environ.get("DB_USER", _leer_env("DB_USER", "")),
                "PASSWORD": os.environ.get("DB_PASSWORD", _leer_env("DB_PASSWORD", "")),
                "HOST": os.environ.get("DB_HOST", _leer_env("DB_HOST", "")),
                "PORT": os.environ.get("DB_PORT", _leer_env("DB_PORT", "5432")),
                "OPTIONS": {"sslmode": "require"},
            }
        }

    return {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),
        }
    }


# Quick-start development settings - unsuitable for production.
# See Django deployment checklist docs for production settings.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "[ENCRYPTION_KEY]"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

globals()["ALLOWED_HOSTS"] = ["*"]


# Application definition

globals()["INSTALLED_APPS"] = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "almacen",
    "inventario",
    "mantenimiento",
    "prestamo",
    "usuario",
    "configuracion",
]

globals()["MIDDLEWARE"] = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

globals()["TEMPLATES"] = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

globals()["DATABASES"] = _build_database_settings()


# Password validation
# See AUTH_PASSWORD_VALIDATORS in Django reference settings docs.

globals()["AUTH_PASSWORD_VALIDATORS"] = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "staticfiles"  # Optional: for deployment
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
globals()["STATICFILES_DIRS"] = [
    "static",
]
